/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00450d',
        'on-primary': '#ffffff',
        'primary-container': '#1b5e20',
        'on-primary-container': '#90d689',
        'inverse-primary': '#91d78a',
        secondary: '#3a5f94',
        'on-secondary': '#ffffff',
        'secondary-container': '#9fc2fe',
        'on-secondary-container': '#294f83',
        tertiary: '#6b1d3d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#883454',
        'on-tertiary-container': '#ffaec6',
        background: '#f7fbf1',
        'on-background': '#191d17',
        surface: '#f7fbf1',
        'on-surface': '#191d17',
        'on-surface-variant': '#41493e',
        'surface-dim': '#d8dbd2',
        'surface-bright': '#f7fbf1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f5ec',
        'surface-container': '#ecefe6',
        'surface-container-high': '#e6e9e0',
        'surface-container-highest': '#e0e4db',
        'surface-variant': '#e0e4db',
        outline: '#5c6458',
        'outline-variant': '#c0c9bb',
        error: '#a00000',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d322c',
        'inverse-on-surface': '#eff2e9',
        'surface-tint': '#2a6b2c',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-sm': ['28px', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '80px',
        'margin-mobile': '16px',
        unit: '8px',
        'container-max-width': '1280px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      boxShadow: {
        'card': '0 4px 12px -4px rgba(0,69,13,0.10), 0 1px 3px -1px rgba(0,0,0,0.06)',
        'card-hover': '0 12px 24px -8px rgba(0,69,13,0.15), 0 4px 8px -4px rgba(0,69,13,0.08)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
