// Dados estáticos dos 28 espaços culturais do Acre
// Usado como fallback quando Directus não está disponível

interface EspacoEstatico {
  id: number;
  nome: string;
  slug: string;
  categoria: 'museu' | 'teatro' | 'biblioteca' | 'espaco_memoria' | 'centro_cultural';
  descricao: string;
  endereco: string;
  latitude: number | null;
  longitude: number | null;
  horario_funcionamento: string;
  imagem: string | null;
  status: 'published';
}

type TipoEspaco = EspacoEstatico['categoria'];

const horarios: Record<TipoEspaco, string> = {
  biblioteca: 'Segunda a Sexta, 8h às 17h',
  museu: 'Terça a Domingo, 9h às 18h',
  teatro: 'Conforme programação',
  centro_cultural: 'Terça a Domingo, 10h às 20h',
  espaco_memoria: 'Segunda a Sexta, 8h às 17h',
};

const descricoes: Record<TipoEspaco, string> = {
  biblioteca: 'Espaço dedicado à leitura, pesquisa e acesso ao conhecimento, oferecendo acervo bibliográfico e atividades de incentivo à leitura para a comunidade.',
  museu: 'Espaço de preservação, pesquisa e exposição do patrimônio histórico, artístico e cultural do Estado do Acre.',
  teatro: 'Palco para apresentações de artes cênicas, espetáculos musicais, dança e manifestações culturais.',
  centro_cultural: 'Espaço multifuncional dedicado à promoção de atividades artísticas, culturais e educacionais para a comunidade.',
  espaco_memoria: 'Espaço dedicado à preservação e difusão da memória política, histórica e cultural do Acre.',
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export const espacosEstaticos: EspacoEstatico[] = [
  {
    id: 1,
    nome: 'Biblioteca Pública Eliomar De Souza',
    slug: slugify('Biblioteca Pública Eliomar De Souza'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Rua Capitão Pedro Vasconcelos, 175',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 2,
    nome: 'Biblioteca Pública Estadual Adonay Barbosa',
    slug: slugify('Biblioteca Pública Estadual Adonay Barbosa'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Av. Getúlio Vargas, 389 – Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 3,
    nome: 'Biblioteca Pública Estadual Da Floresta',
    slug: slugify('Biblioteca Pública Estadual Da Floresta'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Via Parque Da Maternidade, S/N - Capoeira',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 4,
    nome: 'Museu Dos Povos Acreanos',
    slug: slugify('Museu Dos Povos Acreanos'),
    categoria: 'museu',
    descricao: descricoes.museu,
    endereco: 'Av. Epaminondas Jácome, 2700 - Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.museu,
    imagem: null,
    status: 'published',
  },
  {
    id: 5,
    nome: 'FEM – Casa da Cultura Arte Viva',
    slug: slugify('FEM – Casa da Cultura Arte Viva'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Rua 17 De Novembro, 1291, 6 De Agosto',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 6,
    nome: 'Biblioteca Pública Padre Trindade',
    slug: slugify('Biblioteca Pública Padre Trindade'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Av. Rodrigues Alves, No 443, Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 7,
    nome: 'Biblioteca Pública Estadual Ancelmo Lessa',
    slug: slugify('Biblioteca Pública Estadual Ancelmo Lessa'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Rua Coronel Juvêncio De Menezes, 301 - Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 8,
    nome: 'Museu De Xapuri',
    slug: slugify('Museu De Xapuri'),
    categoria: 'museu',
    descricao: descricoes.museu,
    endereco: 'Rua Coronel Brandão, 160/ Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.museu,
    imagem: null,
    status: 'published',
  },
  {
    id: 9,
    nome: 'Museu Da Borracha',
    slug: slugify('Museu Da Borracha'),
    categoria: 'museu',
    descricao: descricoes.museu,
    endereco: 'Av. Ceará, 1441 – Bairro Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.museu,
    imagem: null,
    status: 'published',
  },
  {
    id: 10,
    nome: 'Casa De Leitura Chico Mendes',
    slug: slugify('Casa De Leitura Chico Mendes'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Rua Gregório Filho, 80 – Bairro Chico Mendes',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 11,
    nome: 'Tentamen',
    slug: slugify('Tentamen'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Rua 24 De Janeiro, 269 – Bairro 6 De Agosto',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 12,
    nome: 'Teatro Plácido De Castro',
    slug: slugify('Teatro Plácido De Castro'),
    categoria: 'teatro',
    descricao: descricoes.teatro,
    endereco: 'Av. Getúlio Vargas, 2703 - Bosque',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.teatro,
    imagem: null,
    status: 'published',
  },
  {
    id: 13,
    nome: 'Memorial Dos Autonomistas',
    slug: slugify('Memorial Dos Autonomistas'),
    categoria: 'espaco_memoria',
    descricao: descricoes.espaco_memoria,
    endereco: 'Av. Getúlio Vargas, 309 – Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.espaco_memoria,
    imagem: null,
    status: 'published',
  },
  {
    id: 14,
    nome: 'Teatro Hélio Melo',
    slug: slugify('Teatro Hélio Melo'),
    categoria: 'teatro',
    descricao: descricoes.teatro,
    endereco: 'Av. Getúlio Vargas, 309 – Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.teatro,
    imagem: null,
    status: 'published',
  },
  {
    id: 15,
    nome: 'Cine Teatro Recreio',
    slug: slugify('Cine Teatro Recreio'),
    categoria: 'teatro',
    descricao: descricoes.teatro,
    endereco: 'R. Sen. Eduardo Assmar - 6 de Agosto',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.teatro,
    imagem: null,
    status: 'published',
  },
  {
    id: 16,
    nome: 'Usina De Artes João Donato',
    slug: slugify('Usina De Artes João Donato'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Av. Parque Das Acácias, 1.155 – Zona B, Setor 4',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 17,
    nome: 'Biblioteca Pública Estadual João Donato',
    slug: slugify('Biblioteca Pública Estadual João Donato'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Av. Parque Das Acácias, 1.155 – Zona B, Setor 4',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 18,
    nome: 'Teatro Barracão Matias',
    slug: slugify('Teatro Barracão Matias'),
    categoria: 'teatro',
    descricao: descricoes.teatro,
    endereco: 'Estrada Da Sobral, 425 – Sobral',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.teatro,
    imagem: null,
    status: 'published',
  },
  {
    id: 19,
    nome: 'Biblioteca Pública Estadual Vó Nazaré',
    slug: slugify('Biblioteca Pública Estadual Vó Nazaré'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Estrada Da Sobral, 425 – Sobral',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
  {
    id: 20,
    nome: 'Casarão',
    slug: slugify('Casarão'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Av. Brasil N° 310 - Centro',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 21,
    nome: 'Centro de Formação Cultural',
    slug: slugify('Centro de Formação Cultural'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Via Parque - Bosque, Rio Branco - AC',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 22,
    nome: 'Casa Cultural Canal Das Artes',
    slug: slugify('Casa Cultural Canal Das Artes'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'R. Granada, 50 - Conj - 4 1',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 23,
    nome: 'Teatro Dos Náuas',
    slug: slugify('Teatro Dos Náuas'),
    categoria: 'teatro',
    descricao: descricoes.teatro,
    endereco: 'Rua Antônio Costeira, S/N – Bairro João Alves',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.teatro,
    imagem: null,
    status: 'published',
  },
  {
    id: 24,
    nome: 'Museu E Memorial José Augusto',
    slug: slugify('Museu E Memorial José Augusto'),
    categoria: 'museu',
    descricao: descricoes.museu,
    endereco: 'Av. Desembargador Távora, Lotes 14 E 15 – Quadra',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.museu,
    imagem: null,
    status: 'published',
  },
  {
    id: 25,
    nome: 'Salão Cordélia Lima',
    slug: slugify('Salão Cordélia Lima'),
    categoria: 'centro_cultural',
    descricao: descricoes.centro_cultural,
    endereco: 'Rua do Purus nº 424, João Alves',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.centro_cultural,
    imagem: null,
    status: 'published',
  },
  {
    id: 26,
    nome: 'Casa De Leitura',
    slug: slugify('Casa De Leitura'),
    categoria: 'biblioteca',
    descricao: descricoes.biblioteca,
    endereco: 'Avenida Castelo Branco – Parque Buritizal',
    latitude: null,
    longitude: null,
    horario_funcionamento: horarios.biblioteca,
    imagem: null,
    status: 'published',
  },
];
